name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --watchAll=false
      - run: npm run build
      - run: npx --no-install source-map-explorer "build/static/js/*.js" --json > bundle-report.json
      - run: npx --yes @lhci/cli autorun --upload.target=temporary-public-storage || echo "Lighthouse failed"
